apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flask-microservice
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Charungooa/flask-microservices
  ref:
    branch: main