apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flask-microservice
  namespace: flask-dev
spec:
  interval: 5m
  releaseName: flask-microservice
  chart:
    spec:
      chart: ./charts/flask-microservice
      sourceRef:
        kind: GitRepository
        name: flask-microservice
        namespace: flux-system
      interval: 1m
      reconcileStrategy: Revision
  values:
    replicaCount: 1
    image:
      repository: docker.io/topaz82/flask-microservices
      tag: "latest"
    service:
      type: NodePort
    autoscaling:
      enabled: false